name: Build UEDumper
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 强制修正 Git 协议
        run: |
          git config --global url."https://github.com/".insteadOf git://github.com/
          git config --global url."https://".insteadOf git://

      - name: 拉取代码（含子模块）
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 下载并配置 NDK r25c
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          echo "NDK_HOME=${{ github.workspace }}/android-ndk-r25c" >> $GITHUB_ENV
          echo "${{ github.workspace }}/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: 执行官方构建脚本
        run: |
          cd AndUEDumper
          chmod +x build.sh
          # 自动输入2并执行脚本
          echo "2" | ./build.sh

      # 这里的路径严格对应你刚才那版脚本里的 NDK_LIBS_OUT 路径
      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: UEDump3r-binaries
          path: AndUEDumper/ndk_build/libs/**/UEDump3r*
