name: Build UEDumper (External ImGui)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 修正子模块协议
        run: git config --global url."https://github.com/".insteadOf git://github.com/

      # 这里使用了原作者的 external-gui 分支！
      - name: 拉取外部 ImGui 分支代码
        uses: actions/checkout@v4
        with:
          repository: MJx0/AndUEDumper
          ref: external-gui
          submodules: 'recursive'

      - name: 配置 NDK r25c
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip
          echo "NDK_HOME=${{ github.workspace }}/android-ndk-r25c" >> $GITHUB_ENV
          echo "${{ github.workspace }}/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      # 重点：这里必须选 1 (CMake)，才能把 ImGui 渲染库编译进去！
      - name: 执行 CMake 构建 (包含 ImGui 支持)
        run: |
          cd AndUEDumper
          chmod +x build.sh
          echo "1" | ./build.sh

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: UEDump3r-GUI-Binary
          path: AndUEDumper/ndk_build/libs/**/UEDump3r
